export const WORDS = [
  'cosmic',
  'waffle',
  'velvet',
  'cactus',
  'lunar',
  'pickle',
  'amber',
  'phantom',
  'crimson',
  'breeze',
  'marble',
  'quartz',
  'nebula',
  'fossil',
  'indigo',
  'tundra',
  'mosaic',
  'orchid',
  'rustic',
  'beacon',
  'prism',
  'cobalt',
  'dusk',
  'ember',
  'frost',
  'glyph',
  'hazel',
  'ivory',
  'jade',
  'kiwi',
  'lemon',
  'mango',
  'neon',
  'opal',
  'plume',
  'raven',
  'sage',
  'titan',
  'umbra',
  'viper',
  'waltz',
  'zenith',
  'aurora',
  'basalt',
  'cedar',
  'delta',
  'echo',
  'flint',
  'grove',
  'hollow',
  'jasper',
  'kelp',
];

export function getRandomPhrase() {
  const first = Math.floor(Math.random() * WORDS.length);
  const second = Math.floor(Math.random() * (WORDS.length - 1));
  const secondIdx = second >= first ? second + 1 : second;
  return WORDS[first] + ' ' + WORDS[secondIdx];
}
